typography_spectrum: 0.8206606346648186
color:
  brandStrength: 0.3594032912515104
  lightness: 0.03214286733418703
  saturation: 0.49311526375822723
  rhythmicContrast: 0.656428225338459
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.263429208425805
author:
  name: Rawdee
  email: info@rawdeegaming.com
  url: 'http://www.rawdeegaming.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f5d60afa-7473-45ff-89b6-593b9d136be2.png
name: Rawdee Gaming
title: All about Rawdee
description: Who's the crazy dude in your monitor?
